### ISSUE TITLE
Update airport and current location icon

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#35]
Aaron is sending new icons for airports and the icon for when a user clicks a location. Just need to add those.

**Comment by stdavis** [comment]
@jpechmann Aaron has already sent me a few current location icons. Is it one of those? What color did you decide on?

**Comment by jpechmann** [comment]
Yup! I believe it is one of those. We are sticking with blue for transportation.

**Comment by stdavis** [comment]
What color for the current location icon? I think that he sent me a red and an orange one. Which one do I use? Or will he let me know?

The back story is that he originally sent me two different current location icons. Both of which were colored very similar to existing markers so that they didn't stand out at all. For example, here's one:
![screenshot](http://i.imgur.com/ulKwqP0.png)

This is why Steve and I came up with the pink. But as Aaron told me yesterday: "ummmmmmm, yeah.  we can't have pink". Which is cool with me. I understand if it breaks some sort of designer rule or something. I just suggest that we choose a color that stands out from the rest of the markers. I told him that but he hasn't given me any other colors yet.

**Comment by stdavis** [comment]
Superseded by #44
