### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#44]
Switch blue and yellow, so yellow is transportation, and blue is utilities. Also, we are thinking an orangey/red, more orange, for the current location icon.

**Comment by stdavis** [comment]
OK. So should I ask for a new icon from Aaron or use one of the orange ones that he has already given me below?
![image](https://cloud.githubusercontent.com/assets/1326248/5721543/1dd0724c-9af0-11e4-8ea3-de970fe7c386.png)

![image](https://cloud.githubusercontent.com/assets/1326248/5721541/13fe1cce-9af0-11e4-9da7-8e833f716382.png)

It's much easier for him to change the colors rather than me.

**Comment by stdavis** [comment]
Also, we'll need to ask Aaron for new Airports and Light rail icons that are blue.

**Comment by jpechmann** [comment]
I'm voting for the first one. Thanks!

**Comment by jpechmann** [comment]
You mean airport and light rail icons that are yellow?

**Comment by stdavis** [comment]
Yes, I editing my comment after posting. They also need to be 24x35 pixels.

**Comment by jpechmann** [comment]
Okay, I'll ask him for those.
