### ISSUE TITLE
Retain map settings in url

### ISSUE THREAD

**Issue by jpechmann** [agrc/bb-econ#75]
Retain what map layers are drawn and the map extent in the webpage url.

**Comment by jpechmann** [comment]
I should have added the use case that this is wanted for. GOED wants to be able to link to the map form another website with enterprise zones drawn, and have the option to be zoomed to where a certain enterprise zone is.

**Comment by brigsz** [comment]
Just so you know, there is an enterprise zones website, however it does not have this functionality.  Would they want that one to have this functionality?

**Comment by jpechmann** [comment]
Matt, What is the url to the enterprise zones websites? Did you talked to Kelleigh and/or the others at GOED about that website when you were discussing enterprise zones with them? I haven't spoken to Kelleigh at all about that website, and I'm not sure if she's the steward of it or not..

**Comment by brigsz** [comment]
The Link to the Enterprise zones comes from this GOED page.  http://business.utah.gov/programs/incentives/enterprise-zones/   It the links to http://mapserv.utah.gov/enterpriseZones/   I doubt she is the steward, and the general goed site has been updated with a variety of things since I looked at it last.  We have the same for Recycle zones, but it is still in test.  I am hoping Sean's work with them will either raise the issue or put it to bed once and for all.
